# Generated by Django 4.2.4 on 2023-11-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_verified_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(blank=True, default=False, verbose_name='верифицирован'),
        ),
    ]
