# Generated by Django 4.2.4 on 2023-11-10 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('set_published', 'Can publish posts')], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
