# Generated by Django 4.2.4 on 2023-11-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_options_alter_product_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(choices=[(True, 'опубликовать'), (False, 'снять с публикации')], default=False, verbose_name='публикация'),
        ),
    ]
